<?php

namespace Container0MXCAuJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVarDumper_DumpServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'var_dumper.dump_server' shared service.
     *
     * @return \Symfony\Component\VarDumper\Server\DumpServer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'var-dumper'.\DIRECTORY_SEPARATOR.'Server'.\DIRECTORY_SEPARATOR.'DumpServer.php';

        return $container->privates['var_dumper.dump_server'] = new \Symfony\Component\VarDumper\Server\DumpServer('tcp://'.$container->getEnv('string:VAR_DUMPER_SERVER'), ($container->privates['monolog.logger.debug'] ?? $container->load('getMonolog_Logger_DebugService')));
    }
}
