<?php

namespace Container4kSnFAy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_83wt11CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.83wt11C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.83wt11C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FilmsController::create' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\FilmsController::delete' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\FilmsController::edit' => ['privates', '.service_locator.c5BISKB', 'get_ServiceLocator_C5BISKBService', true],
            'App\\Controller\\FilmsController::index' => ['privates', '.service_locator.tbYGSq6', 'get_ServiceLocator_TbYGSq6Service', true],
            'App\\Controller\\FilmsController::show' => ['privates', '.service_locator.tbYGSq6', 'get_ServiceLocator_TbYGSq6Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FilmsController:create' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\FilmsController:delete' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\FilmsController:edit' => ['privates', '.service_locator.c5BISKB', 'get_ServiceLocator_C5BISKBService', true],
            'App\\Controller\\FilmsController:index' => ['privates', '.service_locator.tbYGSq6', 'get_ServiceLocator_TbYGSq6Service', true],
            'App\\Controller\\FilmsController:show' => ['privates', '.service_locator.tbYGSq6', 'get_ServiceLocator_TbYGSq6Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FilmsController::create' => '?',
            'App\\Controller\\FilmsController::delete' => '?',
            'App\\Controller\\FilmsController::edit' => '?',
            'App\\Controller\\FilmsController::index' => '?',
            'App\\Controller\\FilmsController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FilmsController:create' => '?',
            'App\\Controller\\FilmsController:delete' => '?',
            'App\\Controller\\FilmsController:edit' => '?',
            'App\\Controller\\FilmsController:index' => '?',
            'App\\Controller\\FilmsController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
