<?php

namespace Container4kSnFAy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Psy\Configuration' shared service.
     *
     * @return \Psy\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psy'.\DIRECTORY_SEPARATOR.'psysh'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Configuration.php';

        $container->privates['Psy\\Configuration'] = $instance = new \Psy\Configuration();

        $instance->setHistoryFile(($container->targetDir.''.'/psysh_history'));

        return $instance;
    }
}
