<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.bff8fc39.js',
                '/build/465.f7fb980e.js',
                '/build/app.c5b9e4a3.js',
            ],
            'css' => [
                '/build/app.ce36c509.css',
            ],
        ],
    ],
],

]];
